dest: "wp-content/themes/twentysixteen/build"
productionSuffix: ".min"
copies:
  -
    src: "wp-content/themes/twentysixteen/assets/images"
    files:
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.svg"
    dest: "wp-content/themes/twentysixteen/build/images"
  -
    src: "wp-content/themes/twentysixteen/assets/fonts"
    files:
      - "**/*"
    dest: "wp-content/themes/twentysixteen/build/fonts"
assets:
  -
    type: "styles"
    output: "main.css"
    src: "wp-content/themes/twentysixteen/assets/scss"
    files:
      - "main.scss"
    watch:
      - "**/*.scss"
  -
    type: "scripts"
    output: "main.js"
    src: "wp-content/themes/twentysixteen/assets/scripts"
    files:
      - "**/*.js"
    watch: true
    lint: true
  -
    type: "scripts"
    src: "bower_components"
    output: "modernizr.js"
    files:
      - "modernizr/modernizr.js"
    lint: false
    watch: false
  -
    type: "scripts"
    src: "bower_components"
    output: "respond.js"
    files:
      - "respond/src/respond.js"
    lint: false
    watch: false

server:
  plugin: "livereload"
  src: "./"
  watch:
    - "wp-content/themes/**/*.php"
