dest: "wp-content/themes/themannekentrip/build"
productionSuffix: ".min"
copies:
  -
    src: "wp-content/themes/themannekentrip/assets/images"
    files:
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.svg"
    dest: "wp-content/themes/themannekentrip/build/images"
  -
    src: "wp-content/themes/themannekentrip/assets/fonts"
    files:
      - "**/*"
    dest: "wp-content/themes/themannekentrip/build/fonts"
assets:
  -
    type: "styles"
    output: "main.css"
    src: "wp-content/themes/themannekentrip/assets/scss"
    files:
      - "main.scss"
    watch:
      - "**/*.scss"
  -
    type: "scripts"
    output: "main.js"
    src: "wp-content/themes/themannekentrip/assets/scripts"
    files:
      - "**/*.js"
    watch: true
    lint: true
  -
    type: "scripts"
    src: "bower_components"
    output: "backbone.js"
    files:
      - "underscore/underscore-min.js"
      - "backbone/backbone-min.js"
    lint: false
    watch: false

server:
  plugin: "livereload"
  src: "./"
  watch:
    - "wp-content/themes/**/*.php"
